### ISSUE TITLE
Pantry add menu does not clear when cancelled

### ISSUE THREAD

**Issue by Jmoore29** [snoberger/meal-prep#100]
Summary:
Pantry add menu does not clear when cancelled

Description:
If go to add an ingredient to the pantry and fill out the fields, but decide I don't need it and close the menu when I go to add a new ingredient again the menu remembers what I have typed in before, then I have to waste time getting rid of something I already didn't want.  

Severity:
Medium

**Comment by snoberger** [comment]
Intended
