### ISSUE TITLE
Prop/Cook/Wait information not displayed

### ISSUE THREAD

**Issue by adrianaregalado** [snoberger/meal-prep#79]
**Summary**
Prep/Cook/Wait information is not being displayed on the app
**Description**
When I was creating a recipe and filling out the steps, it asked me if this step was prep, cook, or wait. After selecting one and submitting the recipe, I did not see this information being displayed anywhere. If this information will not be displayed, then it can be removed from the form.
**Severity**
Medium
**Suggestion**
It would be helpful to see even a small "P", "C", or "W" icon on the left side, indicating which type of step it is.

**Comment by snoberger** [comment]
intended
