### ISSUE TITLE
Recipe steps not able to be reordered

### ISSUE THREAD

**Issue by adrianaregalado** [snoberger/meal-prep#80]
**Summary**
The recipe steps can only be reordered by deleting and recreating the step.
**Description**
As I wrote down some steps, I realized that I forgot to include one earlier. Adding it was pretty difficult since I had to remove many steps in order to include this one step and then I had to recreate the ones I removed. This could potentially be frustrating if the user decides they want to add a step to the beginning of the instructions and they have already written down several steps.
**Severity**
Medium
**Suggestion**
A drag to reorder feature to me would probably look the best, however any kind of implementation would be helpful (arrows to move steps up or down/ a drop down menu on the left side of each step that lets you change the step number)

**Comment by snoberger** [comment]
yeah... not a bug but you right
