### ISSUE TITLE
Not able to check off steps in recipe

### ISSUE THREAD

**Issue by adrianaregalado** [snoberger/meal-prep#81]
**Summary**
Not able to check off steps in recipe
**Description**
This isn't a bug or issue but I thought it would be cool if a user could see a recipe they made and be able to check off the steps they complete as they follow the recipe so they remember where they left off?
**Severity**
None
**Suggestion**
This could just be a simple checkbox next to each step, and there could be a button that allows the user to "Reset" and uncheck all boxes.

**Comment by snoberger** [comment]
thats more of a cook page thing but also not a bug
