### ISSUE TITLE
Pantry and recipe ingredients amount metric is slightly confusing

### ISSUE THREAD

**Issue by adrianaregalado** [snoberger/meal-prep#82]
**Summary**
Pantry and recipe ingredients amount metric is slightly confusing
**Description**
When I went to input my ingredients, it asked me for an amount and a metric. At first I was a little confused, I had written "Potatoes" as the title and "2" as the amount, and the suggestion in the metric section said lbs, and I'm not sure why but I thought it was asking for how many pounds the 2 potatoes weigh. I think it was probably because the three fields were ordered vertically so I thought they were all separate and didn't realize the last 2 fields went together.
**Severity**
Low
**Suggestion**
I think personally if the last 2 fields were next to each other, it would be more clear that they are supposed to be part of one field. I would suggest combining the two fields into one titled "amount" and then have the metrics part be to the right of the numeric part so that it is more clear to the user. Additionally, You could even make the metrics part a drop down menu, although it might end up pretty long.

**Comment by snoberger** [comment]
not a bug
