### ISSUE TITLE
Missing field required error is subtle

### ISSUE THREAD

**Issue by adrianaregalado** [snoberger/meal-prep#83]
**Summary**
Missing field required error is subtle
**Description**
When I was adding an ingredient, I forgot to add the title and I pressed the submit button several times, not realizing that the title was red.
**Severity**
Low
**Suggestion**
I think if you could make some sort of popup or red text saying *Title field required, it would be easier to spot that the user is missing a field.

**Comment by snoberger** [comment]
intended
