### ISSUE TITLE
User has no idea which email they're signed in on

### ISSUE THREAD

**Issue by adrianaregalado** [snoberger/meal-prep#84]
**Summary**
User has no idea which email they're signed in on
**Description**
While I was logged in, I could not see anything about my account, and it could be easy to forget which email was used to sign in.
**Severity**
Low
**Suggestion**
It would be nice if you could click on the profile icon on the top right and in the dropdown menu be able to see which email you are logged onto. Not sure if the profile section contains this information because I was not able to access it.

**Comment by snoberger** [comment]
intended
