### ISSUE TITLE
Edit icon lingers in pantry

### ISSUE THREAD

**Issue by adrianaregalado** [snoberger/meal-prep#88]
**Summary**
Edit icon lingers in pantry
**Description**
In the pantry, I added several random ingredients and sometimes I hovered over them so the edit icon would appear and then moved my mouse away quickly and the edit icon remained. This caused several items to say "edit" and it looked a little strange. See image below.
**Severity**
Low
**Suggestion**
None

![image](https://user-images.githubusercontent.com/36739347/101227724-da2edb00-3666-11eb-8815-9cdb2992c0e7.png)

**Comment by snoberger** [comment]
dont move so fast :)
