### ISSUE TITLE
Errors in login screen are not meaningful

### ISSUE THREAD

**Issue by adrianaregalado** [snoberger/meal-prep#90]
**Summary**
Errors in login screen are not meaningful
**Description**
I tried logging in to my account with the wrong password and it just said failed to authenticate, it did not say why it failed. I also tried creating a second account with the same email as my first account and it just took me back to the login screen but didn’t tell me what the error was.
**Severity**
Medium
**Suggestion**
I would suggest to detect why the user failed to login/register and display that error message on the login page so the user knows what went wrong.

**Comment by snoberger** [comment]
intended
