### ISSUE TITLE
Does not automatically navigate to home page after sign up

### ISSUE THREAD

**Issue by adrianaregalado** [snoberger/meal-prep#91]
**Summary**
Does not automatically navigate to home page after sign up
**Description**
After signing up, the app takes the user back to the login screen and says “Failed to authenticate” which is confusing for the user.
**Severity**
Medium
**Suggestion**
I would suggest either automatically logging in the user after they sign up, directing them back to the login page but autofilling their email from the sign up page onto the login page, or even just displaying a short message that says "Successfully signed up. Please log in."

**Comment by snoberger** [comment]
intended
