### ISSUE TITLE
Data was cleared after logging back in

### ISSUE THREAD

**Issue by adrianaregalado** [snoberger/meal-prep#92]
**Summary**
Data was cleared after logging back in
**Description**
I logged out of my account, created another account and logged into it, then logged out of the second account and back into the first and the recipes were still there but my pantry was cleared.
**Severity**
Medium
**Suggestion**
This bug seems concerning but I was not able to replicate it, so I'm not sure what to make of that.

**Comment by snoberger** [comment]
fixed
