### ISSUE TITLE
Recipe Steps throws error when menu is cancelled if all fields are not filled in

### ISSUE THREAD

**Issue by Jmoore29** [snoberger/meal-prep#95]

**Comment by Jmoore29** [comment]
Summary:
Recipe Steps throws error when menu is cancelled if all fields are not filled in

Description:
When I went to add a step to the recipe right after the menu appeared I tried to close it by clicking on the x in the upper righthand corner. After about a second an error message pops up. I can close this error message and it returns me right back to menu where I left off, but it is possible someone may think the application as crashed as decides to close it all together. 


Severity:
Low

**Comment by snoberger** [comment]
done
