### ISSUE TITLE
Recipe Ingredients should have select options for measurement, not just whatever you enter

### ISSUE THREAD

**Issue by Jmoore29** [snoberger/meal-prep#96]

**Comment by Jmoore29** [comment]
Summary:
Recipe Ingredients should have select options for measurement, not just whatever you enter 

Description:
The filed in the steps menu wen adding a step to a recipe allows to to just enter whatever you want as the measurement units of whatever amount you just specified. I think having a drop down menu of common options, with maybe and other selection allow you to enter something unique would be better. 

Severity:
Medium - Low

**Comment by snoberger** [comment]
this is not a bug, its a suggestion
