### ISSUE TITLE
Recipe Steps, it should be specified what units the time is in, i'm assuming it's min.

### ISSUE THREAD

**Issue by Jmoore29** [snoberger/meal-prep#97]

**Comment by Jmoore29** [comment]
Summary:
Recipe Steps, it should be specified what units the time is in

Description:
The units that the time is in for the recipe steps is not displayed anywhere, i'm gonna assume it's probably supposed to be it minutes, but the field allows you to put in huge numbers if you want, so maye restrict the size of the numbers to can be entered into the field.

Severity:
Low

**Comment by snoberger** [comment]
we are assuming we dont have bad actors in the effort to get it done
